openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app
  license:
    name: Apache 2.0
    url: <http://www.apache.org/licenses/LICENSE-2.0.html>
  description: >
    This is a documentation of contacts app
tags:
  - name: Contacts
    description: Operations about users and contacts
  - name: Auth
    description: Authorization operations
servers:
  - url: http://localhost:3000
  - url: https://contacts-app-x5ll.onrender.com
paths:
  /contacts/{contactId}:
    get:
      $ref: ../swagger/paths/contacts/{contactId}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{contactId}/delete.yaml
  # /contacts:
  #   get:
  #     $ref: ../swagger/paths/students/{id}/get.yaml
  /contacts:
    post:
      $ref: ../swagger/paths/contacts/post.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
